version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/reposilite-backend"
    schedule:
      interval: "monthly"
  - package-ecosystem: "npm"
    directory: "/reposilite-frontend"
    schedule:
      interval: "monthly"
  - package-ecosystem: "npm"
    directory: "/reposilite-site"
    schedule:
      interval: "monthly"
