language: java
sudo: true

jdk:
- openjdk8

install:
  - mvn test-compile -DskipTests=true -B -V

script:
  - sudo /usr/local/maven/bin/mvn test jacoco:report

after_success:
  - bash <(curl -s https://codecov.io/bash) || (sleep 5 && bash <(curl -s https://codecov.io/bash)) || (sleep 5 && bash <(curl -s https://codecov.io/bash)) || (sleep 5 && bash <(curl -s https://codecov.io/bash)) || (sleep 5 && bash <(curl -s https://codecov.io/bash))

notifications:
  email: false
