version: "3.9"
services:
  reposilite:
    image: dzikoysk/reposilite:3.5.27
    #
    # To build from sources:
    #
    # image: reposilite:3.5.27
    # build:
    #  context: .
    #  dockerfile: Dockerfile
    ports:
      - ${PORT}:${PORT}
    env_file:
      - .env
    environment:
      - JAVA_OPTS=-Xmx${MEMORY} ${JAVA_COMPOSE_OPTS}
      - REPOSILITE_OPTS=--port ${PORT} ${REPOSILITE_COMPOSE_OPTS}
    volumes:
      - reposilite-data:/app/data
    restart: unless-stopped
    stdin_open: true
    tty: true
volumes:
  reposilite-data: {}
