# GitHub Actions workflow to automatically build Reposilite.
name: "Gradle"

on:
  push:
    branches: [ "main", "3.0" ]
  pull_request:
    branches: [ "main", "3.0" ]

jobs:
  build:
    name: "Build with Java ${{ matrix.java-version }}"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Use 11 LTS releases and the latest one
        java-version: [ 11, 18 ]
    steps:
    - name: "Checkout repository"
      uses: actions/checkout@v3

    - name: "Fetch git tags" # Required for axion-release-plugin
      run: git fetch --tags --unshallow

    - name: "Validate gradle wrapper"
      uses: gradle/wrapper-validation-action@v1

    - name: "Set up Java ${{ matrix.java-version }}"
      uses: actions/setup-java@v3
      with:
        java-version: "${{ matrix.java-version }}"
        distribution: "adopt"

    - name: "Gradle build"
      uses: gradle/gradle-build-action@v2
      with:
        arguments: ":reposilite-backend:testCoverage"

    - name: "Upload coverage to Codecov"
      uses: codecov/codecov-action@v2
      with:
        files: "./reposilite-backend/build/reports/jacoco/reposilite-backend-report.xml"
        fail_ci_if_error: false
